server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: gubify
